CREATE TABLE IF NOT EXISTS tour_company (
                                            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
                                            name VARCHAR(200) NOT NULL COMMENT '旅游公司名称，唯一',
                                            short_name VARCHAR(100) DEFAULT NULL COMMENT '简称',
                                            registered_address VARCHAR(500) NOT NULL COMMENT '注册地址',
                                            registered_latitude DECIMAL(10,6) DEFAULT NULL COMMENT '注册地址纬度',
                                            registered_longitude DECIMAL(10,6) DEFAULT NULL COMMENT '注册地址经度',
                                            business_address VARCHAR(500) DEFAULT NULL COMMENT '经营地址',
                                            business_latitude DECIMAL(10,6) DEFAULT NULL COMMENT '经营地址纬度',
                                            business_longitude DECIMAL(10,6) DEFAULT NULL COMMENT '经营地址经度',
                                            business_scope VARCHAR(500) DEFAULT NULL COMMENT '经营范围',
                                            business_status TINYINT NOT NULL DEFAULT 1 COMMENT '营业状态：1营业中 2暂停 3已注销',
                                            unified_social_credit_code VARCHAR(50) DEFAULT NULL COMMENT '统一社会信用代码',
                                            legal_representative VARCHAR(100) DEFAULT NULL COMMENT '法定代表人',
                                            registered_capital DECIMAL(18,2) DEFAULT NULL COMMENT '注册资本（万元）',
                                            establishment_date DATE DEFAULT NULL COMMENT '成立日期',
                                            business_term VARCHAR(200) DEFAULT NULL COMMENT '营业期限，如 长期/2020-01-01至2050-01-01',
                                            official_phone VARCHAR(50) DEFAULT NULL COMMENT '官方联系电话（11位校验在应用层）',
                                            emergency_contact VARCHAR(100) DEFAULT NULL COMMENT '紧急联系人',
                                            emergency_phone VARCHAR(50) DEFAULT NULL COMMENT '紧急联系电话（11位校验在应用层）',
                                            official_email VARCHAR(100) DEFAULT NULL COMMENT '官方邮箱',
                                            intro TEXT COMMENT '简介/特色亮点',
                                            logo_url VARCHAR(500) DEFAULT NULL COMMENT 'Logo 图 URL',
                                            website VARCHAR(200) DEFAULT NULL COMMENT '官方网站',
                                            create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                            status TINYINT NOT NULL DEFAULT 1 COMMENT '逻辑状态：1正常 0删除',
                                            PRIMARY KEY (id),
                                            UNIQUE KEY uk_tour_company_name (name),
                                            KEY idx_company_status (business_status),
                                            KEY idx_company_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='旅游公司表';
