CREATE TABLE IF NOT EXISTS tour_route (
                                          id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
                                          name VARCHAR(200) NOT NULL COMMENT '路线名称',
                                          route_type VARCHAR(100) DEFAULT NULL COMMENT '类型：如 红色旅游/绿色旅游/组合 等（文本存储）',
                                          theme_tags VARCHAR(500) DEFAULT NULL COMMENT '主题标签，逗号分隔：如 西红东绿,红色教育,生态康养',
                                          origin_address VARCHAR(255) DEFAULT NULL COMMENT '起点地址',
                                          origin_lat DECIMAL(10,6) DEFAULT NULL COMMENT '起点纬度',
                                          origin_lng DECIMAL(10,6) DEFAULT NULL COMMENT '起点经度',
                                          dest_address VARCHAR(255) DEFAULT NULL COMMENT '终点地址',
                                          dest_lat DECIMAL(10,6) DEFAULT NULL COMMENT '终点纬度',
                                          dest_lng DECIMAL(10,6) DEFAULT NULL COMMENT '终点经度',
                                          days INT DEFAULT NULL COMMENT '行程天数',
                                          difficulty VARCHAR(50) DEFAULT NULL COMMENT '行程难度：如 轻松/适中/挑战',
                                          itinerary TEXT COMMENT '行程安排（文字描述）',
                                          biz_status TINYINT NOT NULL DEFAULT 1 COMMENT '经营状态：1发布 2进行中 3暂停',
                                          target_crowd VARCHAR(200) DEFAULT NULL COMMENT '目标人群',
                                          price_range VARCHAR(100) DEFAULT NULL COMMENT '价格区间：如 2000-5000元/人',
                                          safety_measures TEXT COMMENT '安全措施',
                                          service_guarantee TEXT COMMENT '服务保障',
                                          cost_included TEXT COMMENT '费用包含',
                                          cost_excluded TEXT COMMENT '费用不包含',
                                          create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                          update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                          status TINYINT NOT NULL DEFAULT 1 COMMENT '逻辑状态：1正常 0删除',
                                          PRIMARY KEY (id),
                                          KEY idx_route_status (biz_status),
                                          KEY idx_route_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='旅游路线表';
